In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
ss_arr_1 = np.random.randint(10, size=(2, 2))

In [7]:
print("ss_arr_1\n", ss_arr_1)

ss_arr_1
 [[5 3]
 [1 2]]


In [8]:
ss_arr_2 = np.random.randint(10, size=(2, 2))

In [9]:
print("ss_arr_2\n", ss_arr_2)

ss_arr_2
 [[1 3]
 [9 8]]


In [10]:
np.vstack((ss_arr_1, ss_arr_2))

array([[5, 3],
       [1, 2],
       [1, 3],
       [9, 8]])

In [11]:
np.hstack((ss_arr_1, ss_arr_2))

array([[5, 3, 1, 3],
       [1, 2, 9, 8]])

In [14]:
ss_arr_3 = np.delete(ss_arr_1, 1, 0)
print("ss_arr_3\n", ss_arr_3)

ss_arr_3
 [[5 3]]


In [15]:
ss_arr_4 = np.delete(ss_arr_2, 1, 0)
print("ss_arr_4\n", ss_arr_4)

ss_arr_4
 [[1 3]]


In [16]:
np.column_stack((ss_arr_3, ss_arr_4))

array([[5, 3, 1, 3]])

In [17]:
np.row_stack((ss_arr_3, ss_arr_4))

array([[5, 3],
       [1, 3]])

In [18]:
ss_arr_5 = np.random.randint(10, size=(2, 10))

In [19]:
print("ss_arr_5\n", ss_arr_5)

ss_arr_5
 [[7 4 7 0 5 6 2 7 4 6]
 [9 2 7 8 9 2 9 7 5 3]]


In [20]:
np.hsplit(ss_arr_5, 5)

[array([[7, 4],
        [9, 2]]),
 array([[7, 0],
        [7, 8]]),
 array([[5, 6],
        [9, 2]]),
 array([[2, 7],
        [9, 7]]),
 array([[4, 6],
        [5, 3]])]

In [21]:
np.hsplit(ss_arr_5, (2, 4))

[array([[7, 4],
        [9, 2]]),
 array([[7, 0],
        [7, 8]]),
 array([[5, 6, 2, 7, 4, 6],
        [9, 2, 9, 7, 5, 3]])]